services:
  hello-world:
    image: sbh69/hello-world-color:0.1.2
    ports:
      - "${HOST_PORT:-8080}:80"
    volumes:
      - type: bind
        source: ./app
        target: /usr/share/nginx/html/files
        # /var/lib/docker/volumes/${COMPOSE_PROJECT_NAME}_app/_data:/usr/share/nginx/html
    environment:
      - BACKGROUND_COLOR=${BACKGROUND_COLOR:-lightblue}  # Default color
      - DISPLAY_IMAGE=${DISPLAY_IMAGE:-hello-world.png}  # Default image
