version: '3.8'

services:
  hello-world:
    image: sbh69/hello-world-color:0.1.1
    ports:
      - "${HOST_PORT:-8080}:80"
    volumes:
      - type: volume
        source: app
        target: /usr/share/nginx/html
        volume: 
          # /var/lib/docker/volumes/app/_data/${COMPOSE_PROJECT_NAME}:/usr/share/nginx/html
          subpath: ${COMPOSE_PROJECT_NAME}
    environment:
      - BACKGROUND_COLOR=${BACKGROUND_COLOR:-lightblue}  # Default color
      - DISPLAY_IMAGE=${DISPLAY_IMAGE:-hello-world.png}  # Default image

volumes:
  app:
    name: app
