version: '3.8'

services:
  hello-world:
    image: sbh69/hello-world-color
    ports:
      - "${HOST_PORT:-8080}:80"
    volumes:
      - app-data:/usr/share/nginx/html
    environment:
      - BACKGROUND_COLOR=${BACKGROUND_COLOR:-lightblue}  # Default color
      - DISPLAY_IMAGE=${DISPLAY_IMAGE:-hello-world.png}  # Default image

volumes:
  app-data:
    name: app-data
