version: '2.4'

services:
  hello-world:
    image: sbh69/hello-world-color
    ports:
    - "8080:80"
    env_file:
      - .env
    environment:
      - BACKGROUND_COLOR=${BACKGROUND_COLOR:-lightblue}  # Default color
      - DISPLAY_IMAGE=${DISPLAY_IMAGE:-hello-world.png}  # Default image
